# Brute-force method for solving TSP (Exact Solution)

*Time Complexity: O(n!)
<br>
This is because it generates all possible routes (permutations) of cities. For 
n cities, there are (n−1)! possible routes.*
<br>
*Space Complexity: O(n^2)*

In [66]:
import numpy as np
from itertools import permutations
from time import time

In [ ]:
class TSPBruteForceSolver:
    def __init__(self, distanceMatrix):
        """
        Initialize the TSP solver with the distance matrix.
        :param distanceMatrix: 2D numpy array containing distances between cities
        """
        self.distanceMatrix = distanceMatrix
        self.numCities = distanceMatrix.shape[0]
    
    def solve(self):
        """
        Main function to solve the TSP problem using brute force.
        :return: Tuple containing the best route and the minimum cost
        """
        allRoutes = self.generateAllRoutes()
        bestRoute, minCost = self.findBestRoute(allRoutes)
        return bestRoute, minCost
    
    def generateAllRoutes(self):
        """
        Generate all possible routes starting from city 0, excluding permutations of city 0.
        :return: Permutations of all cities except city 0
        """
        cities = np.arange(self.numCities)
        return permutations(cities[1:])
    
    def findBestRoute(self, allRoutes):
        """
        Find the best route from all possible routes based on minimum cost.
        :param allRoutes: All permutations of possible routes
        :return: Tuple containing the best route and its corresponding cost
        """
        minCost = float('inf')
        bestRoute = None
        
        for route in allRoutes:
            fullRoute = self.buildFullRoute(route)
            routeCost = self.calculateRouteCost(fullRoute)
            if routeCost < minCost:
                minCost = routeCost
                bestRoute = fullRoute
        
        return bestRoute, minCost
    
    def buildFullRoute(self, route):
        """
        Build the full route starting and ending at city 0.
        :param route: Permutation of cities excluding city 0
        :return: Full route including city 0 at both ends
        """
        return (0,) + route + (0,)
    
    def calculateRouteCost(self, route):
        """
        Calculate the total travel cost of a given route.
        :param route: Tuple representing a full route
        :return: Total cost of the route
        """
        totalCost = np.sum(self.distanceMatrix[route[:-1], route[1:]])
        return totalCost

In [ ]:
class TSPApp:
    def __init__(self):
        self.distanceMatrix = None
        self.solver = None
    
    def setDistanceMatrix(self, distanceMatrix):
        self.distanceMatrix = distanceMatrix
        self.solver = TSPBruteForceSolver(distanceMatrix)
    
    def run(self):
        if self.solver is None:
            raise Exception("Distance matrix is not set.")
        
        bestRoute, minCost = self.solver.solve()
        self.displayResults(bestRoute, minCost)
    
    def displayResults(self, bestRoute, minCost):
        print("Best Route:", bestRoute)
        print("Minimum Cost:", minCost)
        self.printPath(bestRoute)
    
    def generateRandomGraph(self, n, max_distance=100):
        distanceMatrix = np.random.randint(1, max_distance+1, size=(n, n))
        np.fill_diagonal(distanceMatrix, 0)
        return distanceMatrix
    
    def printPath(self, path):
        """
        Print the path in array form.
        :param path: Tuple representing the path (e.g., (0, 2, 3, 1, 0))
        """
        path_array = np.array(list(path))
        print("Path :", path_array)

In [69]:
# Initialize and run the application
tspApp = TSPApp()

In [70]:
# Generate a random distance matrix
numNodes = 10
distanceMatrix = tspApp.generateRandomGraph(numNodes)
tspApp.setDistanceMatrix(distanceMatrix)

print("Distance Matrix:\n", distanceMatrix)

Distance Matrix:
 [[  0   5  89  22  70  79  54 100   2  75]
 [ 42   0  30  20  23  88  13  74  50  21]
 [ 91  58   0  20   5  77  81   1  58  72]
 [ 55  90  86   0  58   6  53  76  80  54]
 [ 48  55  60  84   0  89  85  10   4  58]
 [100  78  21  29  75   0   1  33   4  50]
 [ 47  26  64  46  97  94   0  39  92  71]
 [ 31  29  77  81  55  50  70   0  85  85]
 [ 77  45  48   6  69  13  18  56   0  39]
 [ 91 100  23  51  77  35  39  79   5   0]]


In [71]:
start = time()
tspApp.run()
end = time()

Best Route: (0, np.int64(8), np.int64(3), np.int64(5), np.int64(6), np.int64(1), np.int64(9), np.int64(2), np.int64(4), np.int64(7), 0)
Minimum Cost: 131
Path : [0 8 3 5 6 1 9 2 4 7 0]


In [73]:
runtime = end - start
print(f"Run-time = {runtime:.3f} seconds")

Run-time = 2.593 seconds
